### ISSUE TITLE
ERROR: for kibana  Container

### ISSUE THREAD

**Issue by nitishcsb** [shankysharma86/GeneralAutomations#1]
i am getting error on kibana container. "ERROR: for kibana  Container "24a0319a1982" is unhealthy."

![image](https://user-images.githubusercontent.com/67603302/94357073-34358200-00b3-11eb-99fd-59e6d909b41c.png)

**Comment by shankysharma86** [comment]
Hi,

Could you check the log for kibana container and share? Wondering if this could be issue with container.

**Comment by nitishcsb** [comment]
![Uploading Screenshot 2020-10-04 at 12.21.20 PM.png…]()

**Comment by shankysharma86** [comment]
I only see empty comment above. Please could you try sharing the logs again. Also, the OS you are trying this with?

Marking as required more information.

**Comment by shankysharma86** [comment]
@nitishcsb - could you provide with more information? screenshot shows the problem but to identify what went wrong, we would need logs from the kibana container
